### ISSUE TITLE
org-9.7 breaking changes (wrong-type-argument integer-or-marker p nil)

### ISSUE THREAD

**Issue by petermao** [org-noter/org-noter#48] opened 2023-07-09 06:13 UTC
https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/etc/ORG-NEWS?id=5a3224a32524da23f41d39b833612e81e0e8acc9

See section titled:
#### Internal structure of Org parse tree has been changed

**Comment by brabalan** [comment] 2023-07-26 14:42
This is probably related to this, as I have this error when starting org-noter:
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  get-text-property(nil org-noter-session-id)
  org-noter(nil)
  funcall-interactively(org-noter nil)
  call-interactively(org-noter nil nil)
  command-execute(org-noter)
```

I’m using `Org mode version 9.7 (9.7-??-d6f3aed7b @ /Users/schmitta/.emacs.d/.local/straight/build-28.2/org/)`

**Comment by petermao** [comment] 2023-07-26 17:26
Emacs 29.1-rc1 ships with org 9.6.6, which still works fine.  The `--init-directory` cmd line option comes not a minute too soon.  Thank you for the confirmation that we have some work ahead of us to be Org 9.7 compatible.

**Comment by brabalan** [comment] 2023-07-26 18:20
I tried to debug it and it’s difficult to do, as the problem goes away doing interactive debugging…

**Comment by dmitrym0** [comment] 2023-07-31 01:27
I hit this working on #39. Everything works fine in my "main" emacs, but fails in "no-config vanilla" emacs. Finally dawned on me to check which org "vanilla" is installing and it's indeed 9.7-pre.

The error seems to originate [here](https://github.com/org-noter/org-noter/blob/feature%2Forg-roam-integration/org-noter.el#L116).

@petermao this is why my "demo" was failing for us on Thursday.

**Comment by dmitrym0** [comment] 2023-07-31 01:43
After some further investigation.

Execute the following in a buffer that has org-noter notes. Specifically, `(org-element-property :begin ast)` returns `nil` for some reason. I'm not familiar with this code so I'm not sure why it's failing.

```lisp
(setq document-property (org-noter--get-or-read-document-property nil nil))
(setq ast (org-noter--parse-root (vector (current-buffer) document-property)))
(get-text-property (org-element-property :begin ast) org-noter--id-text-property)
    
(pp ast)
```

AST in org 9.6

```
     (headline
    (:raw-value "Jevons_paradox" :begin 80 :end 437 :pre-blank 0 :contents-begin 97 ...)
    (section
     (:begin 97 :end 437 :contents-begin 97 :contents-end 437 :robust-begin 97 ...)
     (property-drawer
      (:begin 97 :end 200 :contents-begin 110 :contents-end 192 :post-blank 2 ...))
     (paragraph
      (:begin 200 :end 437 :contents-begin 200 :contents-end 437 :post-blank 0 ...))))

         (headline
     (:raw-value "Jevons_paradox" :begin 80 :end 835 :pre-blank 0 :contents-begin 97 :contents-end 835 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 80 :NOTER_DOCUMENT "/Users/dmitrymarkushevich/org-roam/chronicles/Jevons_paradox.pdf" :title "Jevons_paradox" :parent
                 (org-data nil #0))
     (section
      (:begin 97 :end 835 :contents-begin 97 :contents-end 835 :post-blank 0 :post-affiliated 97 :parent #0)
      (property-drawer
       (:begin 97 :end 200 :contents-begin 110 :contents-end 192 :post-blank 2 :post-affiliated 97 :parent #1))
      (paragraph
       (:begin 200 :end 439 :contents-begin 200 :contents-end 438 :post-blank 1 :post-affiliated 200 :parent #1))
      (paragraph
       (:begin 439 :end 451 :contents-begin 439 :contents-end 448 :post-blank 3 :post-affiliated 439 :parent #1))
      (paragraph
       (:begin 451 :end 835 :contents-begin 451 :contents-end 835 :post-blank 0 :post-affiliated 451 :parent #1))))
```

AST in 9.7
```
    "(headline
     (:raw-value \"Jevons_paradox\" :begin 80 :end 835 :pre-blank 0 :contents-begin 97 :contents-end 835 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 80 :NOTER_DOCUMENT \"/Users/dmitrymarkushevich/org-roam/chronicles/Jevons_paradox.pdf\" :title \"Jevons_paradox\" :parent
                 (org-data nil #0))
     (section
      (:begin 97 :end 835 :contents-begin 97 :contents-end 835 :post-blank 0 :post-affiliated 97 :parent #0)
      (property-drawer
       (:begin 97 :end 200 :contents-begin 110 :contents-end 192 :post-blank 2 :post-affiliated 97 :parent #1))
      (paragraph
       (:begin 200 :end 439 :contents-begin 200 :contents-end 438 :post-blank 1 :post-affiliated 200 :parent #1))
      (paragraph
       (:begin 439 :end 451 :contents-begin 439 :contents-end 448 :post-blank 3 :post-affiliated 439 :parent #1))
      (paragraph
       (:begin 451 :end 835 :contents-begin 451 :contents-end 835 :post-blank 0 :post-affiliated 451 :parent #1))))
```

**Comment by petermao** [comment] 2023-07-31 23:12
The first `headline` in your 9.6 output looks to be from an earlier state of the notes document.

Content-wise, the second `headline` in 9.6 is identical to 9.7 (modulo the \'s in front of the double-quotes.  My guess is that `org-noter--parse-root` is generating an ast that is incompatible with org 9.7.

**Comment by dmitrym0** [comment] 2023-08-08 19:25
I have pushed my efforts to fix this to a [branch here](https://github.com/org-noter/org-noter/commit/7e08a5e5821e094e8ace6fbc10b19f6267d30b0d). 

Using this branch, I'm able to invoke org-noter with org-9.7-pre and take precise notes. I have not tested this any further.


This seem relevant (from the org changelog):
```diff
+Properties and their values can now be deferred to avoid overheads when
+parsing.  They are calculated lazily, when the value/property is
+requested by getters.
```

Seems like `org-element-property` doesn't return deferred properties, so you have to force them (see additional parameters to `org-element-property` in the branch I linked).

There are a million calls to `org-element-property` so I tried to look for a different approach. I tried wrapping`org-noter--parse-root` with  `org-element-resolve-deferred` -- which claims to resolve everything, but it didn't quite work. I need to dig into this some more.

**Comment by yantar92** [comment] 2023-08-08 19:36
> Seems like org-element-property doesn't return deferred properties, so you have to force them (see additional parameters to org-element-property in the branch I linked).

Nope, it is not needed. `org-element-property` will resolve deferred when called. The breaking part of the change only affect users that used `plist-get` to retrieve properties directly.

**Comment by dmitrym0** [comment] 2023-08-08 20:30
@yantar92 looking at the new definition: `(org-element-property PROPERTY NODE &optional DFLT FORCE-UNDEFER)` what is the purpose of `FORCE-UNDEFER`?

[Adding the optional parameter](https://github.com/org-noter/org-noter/commit/7e08a5e5821e094e8ace6fbc10b19f6267d30b0d#diff-37ccfd104f0c76635b45769a58628b095a217c497234af06f5bb9079f44125b8R117) to `org-element-property` now returns the expected value. I assumed that is happening because I forced the un-deferral, but I'm not so sure.

**Comment by yantar92** [comment] 2023-08-08 20:49
> what is the purpose of FORCE-UNDEFER?

One of the variants of the deferred value is dynamic - every time `org-element-property` is called, the value is re-computed. FORCE-UNDEFER will modify NODE by side effect, replacing the stored value with result of the computation.

**Comment by yantar92** [comment] 2023-08-09 07:27
I tried to clarify the meaning of `FORCE-UNDEFER` better in the docstring. See
https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=f159adc26
https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=8ed388782

**Comment by dmitrym0** [comment] 2023-08-14 03:59
I'm mystified. 

- `ast` object is created on [line 115](https://github.com/org-noter/org-noter/blob/master/org-noter.el#L115).
- [line 116](https://github.com/org-noter/org-noter/blob/master/org-noter.el#L116) fails to return the `:begin` property (`(org-element-property :begin ast)`).

However:

- If I instrument `org-noter--parse-root` and insert  `(org-element-property :begin ast)` right before the final return from function, the call works just fine and returns the correct value (ie `(org-element-property :begin ast)` => `1`).
- Immediately after returning from `org-noter--parse-root`, `(org-element-property :begin ast)` returns a `nil`.

So it seems like something is changing the value of `ast` after it is returned from `org-noter--parse-root`. Very puzzling.

**Comment by yantar92** [comment] 2023-08-14 06:02
> ast object is created on [line 115](https://github.com/org-noter/org-noter/blob/master/org-noter.el#L115).

Side note: In org-noter--parse-root,

    (save-excursion
       (goto-char (point-min))
       (eq 'property-drawer (org-element-type (org-element-at-point)))))

is not reliable - first line may not be top-level property drawer. It might also be a comment. You can instead use `org-before-first-heading-p`.

> [line 116](https://github.com/org-noter/org-noter/blob/master/org-noter.el#L116) fails to return the :begin property ((org-element-property :begin ast)).

I'd pay attention to the `org-element-property` expansion. We had a number of issues related to inlining (this is an inline function) being wrong.

**Comment by dmitrym0** [comment] 2023-08-14 15:58
> Side note: In org-noter--parse-root,
> ...
> is not reliable - first line may not be top-level property drawer. It might also be a comment. You can instead use `org-before-first-heading-p`.
> 

Thanks, logged as a separate issue.

> > [line 116](https://github.com/org-noter/org-noter/blob/master/org-noter.el#L116) fails to return the :begin property ((org-element-property :begin ast)).
> 
> I'd pay attention to the `org-element-property` expansion. We had a number of issues related to inlining (this is an inline function) being wrong.

I'm not sure I'm following, fully. When we byte compile code, we replace function invocation with the body of the function. How can expansion be wrong? More importantly, how can I tell that it's wrong?

**Comment by dmitrym0** [comment] 2023-08-21 00:22
Spent a bit of time on this today:

- `debug-on-entry` does not seem to be doing anything.
- `M-x disassemble org-element-property` yields this:

```
byte code for org-element-property:
  args: (arg1 arg2 &optional arg3 arg4)
0	constant  apply
1	constant  debug--implement-debug-on-entry
2	stack-ref 2
``` 

which seems to indicate that the `debug-on-entry` is enabled...thus org-noter is calling the wrong version of `org-element-property`.

It seems @yantar92 is correct and I'm loading more than one version of org somehow. I'll create a sandbox that does not use straight.el and try to load everything manually to verify this.

**Comment by yantar92** [comment] 2023-08-21 04:02
Dmitry ***@***.***> writes:

> - `debug-on-entry` does not seem to be doing anything.
> ...
> which seems to indicate that the `debug-on-entry` is enabled...thus org-noter is calling the wrong version of `org-element-property`.

No. `org-element-property' is inlined. `debug-on-entry' won't do
anything because no actual call to it will happen. You need to debug the
caller instead.

> It seems @yantar92 is correct and I'm loading more than one version of org somehow. I'll create a sandbox that does not use straight.el and try to load everything manually to verify this.

If you are using straight.el, you are most likely experiencing
https://github.com/radian-software/straight.el/issues/1107, which has
only been fixed on develop branch.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by dmitrym0** [comment] 2023-08-21 14:59
> If you are using straight.el, you are most likely experiencing [radian-software/straight.el#1107](https://github.com/radian-software/straight.el/issues/1107), which has only been fixed on develop branch.

Indeed, it seems like the same issue. I manually removed org-9.6 packaged with my emacs 28.2 and it worked fine.

**Comment by petermao** [comment] 2023-08-23 06:08
> Indeed, it seems like the same issue. I manually removed org-9.6 packaged with my emacs 28.2 and it worked fine.

Doesn't Org-9.5 come with Emacs 28.2?  Org-9.6 comes with Emacs 29.1.

**Comment by dmitrym0** [comment] 2023-08-23 17:40
> > Indeed, it seems like the same issue. I manually removed org-9.6 packaged with my emacs 28.2 and it worked fine.
> 
> Doesn't Org-9.5 come with Emacs 28.2? Org-9.6 comes with Emacs 29.1.

You're probably right, my daily driver emacs has org 9.6, that's probably why I got confused. Bottom line -- removing built in org manually resolved this issue for me.

**Comment by petermao** [comment] 2023-08-26 06:41
Running `Org mode version 9.7-pre (release_9.6.7-690-g3ec093 @ /home/peterm/emacs/org-mode/lisp/)`, which is ~1 month worth of commits ahead of what @brabalan was using, I find that I can open Moby Dick from our tests directory without errors.  It is, however, painfully slow!

On the next org-mode commit, I see a different error popping up, for which I've registered as Issue #61 here.

**Comment by yantar92** [comment] 2023-08-26 06:50
Peter Mao ***@***.***> writes:

> ...  It is, however, painfully slow!

Is the slowness caused by Org itself, or is it something else?

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by petermao** [comment] 2023-08-26 22:38
> Is the slowness caused by Org itself, or is it something else?
I'll have to bisect again, looking at speed.  I have notice that 9.6 is slower than 9.5, with no changes to org noter (see Issue #29).  I'll get at this in an organized way when I have some time.

Thank you for your engagement on our maintenance issues!

**Comment by rgri** [comment] 2023-08-26 23:13
So, is a fix for this issue to remove the old version of org mode manually?

**Comment by dmitrym0** [comment] 2023-08-27 00:48
> So, is a fix for this issue to remove the old version of org mode manually?

It’s a quick and ugly fix. There’s  apparently a straight.el fix in the works.

**Comment by petermao** [comment] 2023-08-27 01:18
@yantar92 
> ... It is, however, painfully slow!
> Is the slowness caused by Org itself, or is it something else?

Yes, it appears to be Org.  I'm going to open up what I found today as a new issue (#63)

**Comment by petermao** [comment] 2023-09-06 04:16
@dmitrym0 Can you verify that the latest org-noter works with the latest org-mode?  (using speed-test or otherwise).

If so, we can close this issue and #29.

**Closed** 2023-09-22 18:11 UTC
Labels: help wanted
